# Generated by Django 4.2.19 on 2025-03-15 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hobbytrends',
            unique_together=set(),
        ),
    ]
