# Generated by Django 4.2.19 on 2025-03-15 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneRecommendations',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_keywords', models.JSONField(default=list)),
                ('recommendations', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hobby_id', models.ForeignKey(db_column='hobby_id', on_delete=django.db.models.deletion.CASCADE, to='hobbies.hobbykeywords')),
            ],
            options={
                'verbose_name': 'Phone recommendation',
                'verbose_name_plural': 'Phone recommendations',
                'db_table': 'phone_recommendations',
                'managed': True,
            },
        ),
    ]
