# Generated by Django 4.2.19 on 2025-03-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresults',
            name='freq_ratio_apple',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='freq_ratio_samsung',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='related_words_apple',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='related_words_samsung',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='sentiment_apple_ratio',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='sentiment_apple_score',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='sentiment_samsung_ratio',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='sentiment_samsung_score',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
