# Generated by Django 4.2.19 on 2025-03-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_analysisresults_freq_ratio_apple_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresults',
            name='keyword_monthly_trend',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='sentiment_top_sentences',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
