# Generated by Django 4.2.19 on 2025-03-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_analysisresults_keyword_monthly_trend_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisresults',
            old_name='analysis_summary',
            new_name='summary_page_1',
        ),
        migrations.AddField(
            model_name='analysisresults',
            name='summary_page_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresults',
            name='summary_page_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
