# Generated by Django 4.2.19 on 2025-03-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_rename_analysis_summary_analysisresults_summary_page_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisresults',
            old_name='summary_page_1',
            new_name='summary_page_1_1',
        ),
        migrations.RenameField(
            model_name='analysisresults',
            old_name='summary_page_2',
            new_name='summary_page_1_2',
        ),
        migrations.AddField(
            model_name='analysisresults',
            name='summary_page_2_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresults',
            name='summary_page_2_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
