# Generated by Django 4.2.19 on 2025-03-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_rename_summary_page_1_analysisresults_summary_page_1_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisresults',
            old_name='summary_page_2_1',
            new_name='summary_page_2',
        ),
        migrations.RemoveField(
            model_name='analysisresults',
            name='summary_page_2_2',
        ),
    ]
