# Generated by Django 4.2.19 on 2025-03-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_rename_summary_page_2_1_analysisresults_summary_page_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresults',
            name='summary_page_2_1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
