# Generated by Django 4.2.19 on 2025-03-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_analysisresults_summary_page_2_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisresults',
            old_name='summary_page_2',
            new_name='summary_page_2_2',
        ),
    ]
