# Generated by Django 4.2.19 on 2025-03-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbcrawledDanawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoring', models.TextField(blank=True, null=True)),
                ('market', models.TextField(blank=True, null=True)),
                ('purchasing_date', models.TextField(blank=True, null=True)),
                ('review_title', models.TextField(blank=True, null=True)),
                ('review_content', models.TextField(blank=True, null=True)),
                ('item', models.TextField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbCrawled_Danawa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbcrawledYoutube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('channel_name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('like_count', models.IntegerField(blank=True, null=True)),
                ('comment_publish_date', models.DateField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbCrawled_Youtube',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbprocessedYoutube',
            fields=[
                ('processed_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('sentence', models.TextField()),
                ('like_count', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(max_length=50)),
                ('sentiment_label', models.CharField(max_length=10)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('comment_publish_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbProcessed_Youtube',
                'managed': True,
            },
        ),
    ]
