# Generated by Django 4.2.19 on 2025-03-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbprocessedDanawa',
            fields=[
                ('processed_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('review_content', models.TextField(blank=True, null=True)),
                ('clean_review', models.TextField(blank=True, null=True)),
                ('sentence', models.TextField(blank=True, null=True)),
                ('nouns', models.TextField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=10, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('scoring', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbProcessed_Danawa',
                'managed': True,
            },
        ),
    ]
