# Generated by Django 4.2.19 on 2025-03-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0002_tbprocesseddanawa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbprocesseddanawa',
            old_name='nouns',
            new_name='noun',
        ),
    ]
